### ISSUE TITLE
Issue on GKE install

### ISSUE THREAD

**Issue by jalberto** [rudderlabs/rudderstack-helm#10]
Using basic install command with helm get:

    Error: apiVersion 'v2' is not valid. The value must be "v1"

probably because https://github.com/rudderlabs/rudderstack-helm/blob/b7d613d0c63c70fbe9f838c9da21b6568eee29c8/templates/_helpers.tpl#L81

And becuase GKE doesn't follow Semver: `GitVersion:"v1.15.9-gke.24"`

Helm version:

    Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**Comment by jalberto** [comment]
I was wrong, it's becuase `Chart.yaml` is set to `apiVersion: v2`

**Comment by snarkychef** [comment]
Our charts are built and tested for Helm3. So, apiversion is set to 2. What do you mean by templates look like Helm-2?

**Comment by harshmanvar** [comment]
i have deployed GKE but getting 404 when opening loadbalancer IP. i have used the example : [https://github.com/rudderlabs/rudderstack-helm/blob/master/workspaceConfig.json.example](https://github.com/rudderlabs/rudderstack-helm/blob/master/workspaceConfig.json.example) for  WorkSpaceConfig.json . 

helm chart deployed successfully after changing v2 but still on load balancer IP getting 404

**Comment by snarkychef** [comment]
We don't have endpoint for `/` in rudder-server. That might be reason you are getting 404 not found. Please try /health to verify if dataplane is up and running.

**Comment by snarkychef** [comment]
Closing this issue as discussion going on differs from the original issue.
