### ISSUE TITLE
External ip - Pending -- Help 

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudderstack-helm#13]
Hi guys, thanks for the amazing work. 
I'm trying to set the backend up using helm. 
I'm using MicroK8s for simplicity reasons. Here are the commands I ran: 
```
git clone git@github.com:rudderlabs/rudderstack-helm.git
cd rudderstack-helm/
microk8s enable dns dashboard registry
microk8s kubectl config view --raw > $HOME/.kube/config
helm install myproject ./ --set rudderWorkspaceToken="MYCODE"
```
When running `kubectl get --namespace default svc -w myproject-rudderstack` I get: 
```
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
myproject-rudderstack   LoadBalancer   10.152.183.212   <pending>     80:31455/TCP   23m
```
or `kubectl get services`
I get:
```
NAME                                        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes                                  ClusterIP      10.152.183.1     <none>        443/TCP        26m
myproject-rudderstack                       LoadBalancer   10.152.183.212   <pending>     80:31455/TCP   24m
myproject-rudderstack-postgresql            ClusterIP      10.152.183.102   <none>        5432/TCP       24m
myproject-rudderstack-postgresql-headless   ClusterIP      None             <none>        5432/TCP       24m
myproject-rudderstack-transformer           ClusterIP      10.152.183.22    <none>        9090/TCP       24m
```

I'm very new to Kubernetes, and I want to have an external IP that I can proxy through Nginx to serve the API URL on a specific domain but I'm stuck here. 
Can you please help? 

I'm trying to run this on a single machine.

**Comment by gane5hvarma** [comment]
@Sshuichi have you looked into this https://github.com/ubuntu/microk8s/issues/200

**Comment by SumanthPuram** [comment]
Thanks @gane5hvarma for looking into this.

@Sshuichi This message in particular.
https://github.com/ubuntu/microk8s/issues/200#issuecomment-441606091

**Comment by SumanthPuram** [comment]
Closing this issue as this needs to be supported in MicroK8s.
