### ISSUE TITLE
Throw error when following the section of Open source Control Plane

### ISSUE THREAD

**Issue by rayspock** [rudderlabs/rudderstack-helm#14]
I was using open source config-generator UI to generate "workspaceConfig.json", but after using this command:
```bash
$ helm install my-release ./ --set backend.controlPlaneJSON=true
```
 I got this error:

```
Error: YAML parse error on rudderstack/templates/configmap-rudder-server.yaml: error converting YAML to JSON: yaml: line 164: did not find expected key
```

**Comment by rayspock** [comment]
The JSON exported from the generator with the indentation and line feeds won't work. I found out its work only when you compact JSON data and remove all whitespace.

**Comment by gane5hvarma** [comment]
Hi @rayspock, we have fixed this issue. Hence closing this issue.

**Comment by rayspock** [comment]
Great work, thanks.

**Comment by harshmanvar** [comment]
i have deployed GKE but getting 404 when opening loadbalancer IP. i have used the example : https://github.com/rudderlabs/rudderstack-helm/blob/master/workspaceConfig.json.example for WorkSpaceConfig.json .

helm chart deployed successfully after changing v2 but still on load balancer IP getting 404

**Comment by gane5hvarma** [comment]
@harshmanvar the loadbalancer url will show you 404. check health endpoint for server status
