### ISSUE TITLE
Load balancer on AWS doesn't use HTTP protocol

### ISSUE THREAD

**Issue by kevinavery** [rudderlabs/rudderstack-helm#18]
Hi, when I run `helm install` on an AWS cluster created using [terraform-aws-eks](https://github.com/rudderlabs/terraform-aws-eks), I get a classic ELB with a TCP listener. The issue is apparently the protocol has to be HTTP (not TCP) in order for it to set the `X-Forwarded-For` header so that `rudder-server` can properly collect the client IP.

**Comment by snarkychef** [comment]
Thanks for pointing this out. We have fixed it now. Please try again.
