### ISSUE TITLE
Repository License

### ISSUE THREAD

**Issue by hugecannon** [rudderlabs/rudderstack-helm#21]
Github's docs report that a repository's default license (when none is provided) is [quite restrictive](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

Has choosing a license for this project simply been an oversight? 
If so, would it be possible to pick and display one so that others know what they can and cannot do with the code?

**Comment by soumyadebm** [comment]
Thanks for pointing it out. This is released under Apache-2.0. Added to the README
