### ISSUE TITLE
Why require 36Gb of storage ?

### ISSUE THREAD

**Issue by samudurand** [rudderlabs/rudderstack-helm#26]
I noticed the required storage for the backend went up from 8Gb to 36Gb with the changes to include Postgresql in the same pod. I am wondering why that would become necessary ? The postgres has its own 100Gb of storage setup.

**Comment by lokey** [comment]
We increased the default storage to 36Gb to be able to support features like event deduplication etc. You can configure it to a lower value too. 
And FYI, Postgresql runs as a separate pod
