### ISSUE TITLE
Versions confusion

### ISSUE THREAD

**Issue by jalberto** [rudderlabs/rudderstack-helm#27]
- Current helm chart for rudder-servers uses version `alpine-1` 2 months old
-  In rudder-server repo latest release is `0.1.9-patch-02` 10 months old

It is not a good idea to use a moving target in production Kubernetes,

Which version is the stable one? Why releases are so old? Why sky is blue? (it is very confussing)

**Comment by snarkychef** [comment]
We have discontinued releases in GitHub repo. Please use `[rudderlabs/rudder-server:1-alpine](https://hub.docker.com/r/rudderlabs/rudder-server/tags?page=1&ordering=last_updated&name=1-alpine)` docker image. We will update the tag to latest stable release. You can expect a new stable release roughly once a month. We have missed updating this before. Sorry about that.

**Comment by jalberto** [comment]
Hello @snarkychef can you please explain why this versioning strategy?

As you know docker images are usually deployed in systems like Kubernetes, these systems have the following characteristics:

- image cache, so the same image is not pulled from the internet every time a container needs to restart/move
- a rollback system, so it allows to well, rollback versions

Using a single tag for every future release brake every production deployment.
